### ISSUE TITLE
Usage with multiple lists (group, dynamic refs)

### ISSUE THREAD

**Issue by ttxtosca** [Alfred-Skyblue/vue-draggable-plus#1]
Hello @Alfred-Skyblue,

I just tested your version of 'vue-draggable', which looks promising due to recent bugs I found with alternatives.

It works fine for a single list (with hooks fashion), as with 2 "connected" lists manually. But I can't make it work for dynamic lists (or nested `v-for`), eg. a first `v-for` for say 2 columns, the second one for the items in each column.

Using recommended methods for "dynamic refs" won't work : 

https://vuejs.org/guide/essentials/template-refs.html#refs-inside-v-for
https://vuejs.org/guide/essentials/template-refs.html#function-refs

Any idea about this use case? Is that even possible with current state of library?

PS: I got these 2 errors : 
```
[vue-draggable-plus]: Root element not found
Uncaught Sortable: `el` must be an HTMLElement, not [object Undefined]
```

**Comment by ttxtosca** [comment]
For more information, I'm using <script setup>. In your examples you put the "useDraggable" code at top level of <script setup> ; so do I, this seems the only way to make it work (any kind of lists setup).

But the method described in https://vuejs.org/guide/essentials/template-refs.html#refs-inside-v-for sets values only when component is mounted. And any try on "useDraggable" on the "onMounted" hook won't activate sortableJs.

So being able to call "useDraggable" on the "onMounted" hook should work. Also tried with dynamic ids, but the issue is the same since we need to wait for the same "onMounted" hook. Alternatively, the library should (re?)evaluate the refs given when the "onMounted" hook is triggered.

By the way, as I said, other setups work fine. So thank you anyway for your work!

**Comment by Alfred-Skyblue** [comment]
Hello, thank you for your feedback. We can add an "immediate" option in the options later, which allows you to activate Sortablejs immediately when the component is mounted. You can then call "start(el)" to initialize it anywhere later. Would this meet your needs?

**Comment by ttxtosca** [comment]
@Alfred-Skyblue Yes I suppose that this may be a solution for such an issue. The simplest workaround/patch that can be produced the better for the moment :)

Too bad I don't use TS, else I would have suggested something, maybe a PR or so. But I already checked the code and may have observations for some needs.

I also tested your version in a tree-like architecture with a recursive component. Which... works but I'm not sure about the now famous anti-pattern that mutating props is nowadays. (1)

I have to test again your lib anyway in the next hours to reproduce (or not!) some bugs I had with alternatives (2). I'll open distinct issues if needed.

PS: For both points (1) and (2), the method `onEnd` is concerned. I think that being able to customize it (I'll be explicit in right time, eg. vue-specific logic) could serve many users in future.

**Comment by Alfred-Skyblue** [comment]
I'm very sorry for the hesitation for some personal reasons. I may have to wait until next Monday to release the new version.

**Comment by ttxtosca** [comment]
It's Ok no worries :) If I have ideas, suggestions or more info I'll comment here or in another issue.

**Comment by Alfred-Skyblue** [comment]
@ttxtosca Hello, I have added the option of "immediate" in version 0.1.1, which allows you to initialize without starting the drag function. You can call the "start" method to activate the drag function when needed. Here is how you can use it:

```ts
const { start } = useDraggable(el, list, {
  immediate: false,
})

onMounted(() => {
  start()
})
```

**Comment by ttxtosca** [comment]
@Alfred-Skyblue Hello, thank you for this patch. It works! But not like in your example.

Eg. It'll work only when calling `useDraggable` in the `onMounted` hook. Plus, `immediate` option has no effect (but it defaults a `false` value I think?) ; but setting `immediate` as `true` does the same thing, and `start()` method is still needed.

What worked is the following: 

```vue
<script setup>
const colrefs = ref([])
const cols = ref([[{name: 'foo'}, {name: 'bar'}, {name: 'baz'}], []])
onMounted(_ => {
  // Will work with vanilla document.getElementById() method too in this hook (instead of dynamic refs)
  // 'immediate' option has no effect ; but `.start()` method is mandatory
  useDraggable(colrefs.value[0], cols.value[0], {group: 'colsgroup'}).start()
  useDraggable(colrefs.value[1], cols.value[1], {group: 'colsgroup'}).start()
})
</script>

<template>
  <div v-for="(col, i) in cols" :key="`col_${i}`" ref="colrefs">
    <div v-for="(item, j) in col" :key="`item_${j}`">{{item.name}}</div>
  </div>
</template>
```

Closing this issue, thanks again! See you

**Comment by Alfred-Skyblue** [comment]
> @ttxtosca Hello, I have added the option of "immediate" in version 0.1.1, which allows you to initialize without starting the drag function. You can call the "start" method to activate the drag function when needed. Here is how you can use it:
> 
> ```ts
> const { start } = useDraggable(el, list, {
>   immediate: false,
> })
> 
> onMounted(() => {
>   start()
> })
> ```

This way works.

**Comment by Alfred-Skyblue** [comment]
@ttxtosca Hello, I have reviewed your request and I believe that using commands would be more appropriate. You can try implementing the following approach:

```html
<template>
  <div>
    <section v-for="(col, i) in cols" :key="`col_${i}`" v-draggable="[col]">
      <div v-for="item in col" :key="item.name">
        {{ item.name }}
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { vDraggable } from 'vue-draggable-plus'
const cols = ref([
  [{ name: 'foo1' }, { name: 'bar1' }, { name: 'baz1' }],
  [{ name: 'foo2' }, { name: 'bar2' }, { name: 'baz2' }]
])
</script>

```

**Comment by ttxtosca** [comment]
@Alfred-Skyblue Yep, looks nicer. Plus It works. Cannot say if it was the case before the patch.

Thank you :)

**Comment by Alfred-Skyblue** [comment]
@ttxtosca Yes! Previously, it was like that, but I only saw your description and didn't see your code, so I didn't take it into consideration.

**Comment by ttxtosca** [comment]
@Alfred-Skyblue Yes my bad. But your addition (ability to `useDraggable` in the `onMounted` hook) should suit certain users I suppose. Me included, for other tricky setups :)
