### ISSUE TITLE
Suggestion: Log Dragging Direction

### ISSUE THREAD

**Issue by Ben-Avrahami** [Alfred-Skyblue/vue-draggable-plus#121]
hey, a small suggestion i have the would benefit me in using this package.
i would like to be able to see the dragged total direction (left/right) in the onEnd event.
maybe there is a way to do it now that im unaware of? 
thanks

**Comment by Alfred-Skyblue** [comment]
newIndex - oldIndex > 0 ? 'right' : 'left'

**Comment by Ben-Avrahami** [comment]
> newIndex - oldIndex > 0 ? 'right' : 'left'
i mean physically, 
my app is a tinder like app, and i have only 1 elements, I'm not dragging inside an array or something.
i just want to know if the item was dragged left or right on the screen to emit the correct event.
also for the same use case, maybe we can allow not bind the dragging to an array, since for some use cases like mine, the dragging shouldn't manipulate the data, only allow dragging for the HTML elements,  onEnd i respond to the dragging event appropriately, but for my use case it shouldn't be bonded to an array.

**Comment by Alfred-Skyblue** [comment]
Can I understand that you need to know the direction of mouse movement when the mouse is clicked and dragged?
