### ISSUE TITLE
如何与elementui的tab结合，使得tabpane可以拖动排序

### ISSUE THREAD

**Issue by Xiaobaishushu25** [Alfred-Skyblue/vue-draggable-plus#128]
主要依赖为：
```
    "element-plus": "^2.4.1",
    "vue": "^3.3.4",
    "vue-draggable-plus": "^0.4.0",
```
这是vue代码：
```js
  <VueDraggable ref="el" v-model="list" target=".el-tabs_nav">
    <el-tabs v-model="activeName" class="demo-tabs" @tab-click="handleClick">
      <el-tab-pane
          v-for="(group, index) in list"
          :key="index"
          class="cursor-move"
          :label="`${group.name}`"
          :name="`${group.name}`"
      >
        {{group.name}}
      </el-tab-pane>
    </el-tabs>
  </VueDraggable>

import { VueDraggable } from 'vue-draggable-plus'
const activeName = ref('first')

const handleClick = (tab, event: Event) => {
  console.log(tab, event)
}
const list = ref([
  {
    name: 'Joao',
    id: 1
  },
  {
    name: 'Jean',
    id: 2
  },
  {
    name: 'Johanna',
    id: 3
  },
  {
    name: 'Juan',
    id: 4
  }
])
```
希望实现的效果：多个tab可以拖动排序。
目前遇到的问题：当设置`target=".el-tabs_nav"`直接不渲染tabpane并报错：
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/76581880/4f383e1f-841f-41fe-874c-383d7648b6ab)

我去掉`target`属性可以正常渲染：
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/76581880/23e879ce-d884-47d9-8fb1-2d10b17ad090)

也尝试过设置`target`分别为`.el-tabs`或者`.el-tabs_item`等都不行...所以该如何正确设置呢？

我是前端新手，已搜索很长时间仍未解决，希望能获得帮助。非常感谢！

**Comment by Alfred-Skyblue** [comment]
期望可以提供在线复现案例

**Comment by Xiaobaishushu25** [comment]
> 期望可以提供在线复现案例

我尝试提供一个在线案例，https://stackblitz.com/edit/vitejs-vite-uvzs1x?file=src%2FApp.vue ，可以正常演示吗？

**Comment by Alfred-Skyblue** [comment]
> 我尝试提供一个在线案例，https://stackblitz.com/edit/vitejs-vite-uvzs1x?file=src%2FApp.vue ，可以正常演示吗？

这个案例运行没有问题啊

**Comment by Alfred-Skyblue** [comment]
target = '.el-tabs__nav' 但是element-plus在内部添加了一些元素，导致数量和list不匹配，自行斟酌

**Comment by Xiaobaishushu25** [comment]
> target = '.el-tabs__nav' 但是element-plus在内部添加了一些元素，导致数量和list不匹配，自行斟酌

好的，可以了，感谢解答
