### ISSUE TITLE
Is there any way to Lock element on the same place? (disable sort)

### ISSUE THREAD

**Issue by TheKucel** [Alfred-Skyblue/vue-draggable-plus#129]
I need to disable sort for specific element, but not for all list
In SortableJS/Vue.Draggable we have `:move` props, but here i can't see any of these

**Comment by nfunwigabga** [comment]
Did you find a way to do this?

**Comment by nfunwigabga** [comment]
Got it.
```js
onMove(e){
        if (e.related.classList.contains('non-draggable')) return false;
    }
```
