### ISSUE TITLE
Reactive props for VueDraggable component not working

### ISSUE THREAD

**Issue by jimzrt** [Alfred-Skyblue/vue-draggable-plus#13]
It seems that props passed to the VueDraggable component cannot be dynamic / be changed later.
Example: [https://stackblitz.com/edit/vue-ufe6kx?file=src/App.vue](https://stackblitz.com/edit/vue-ufe6kx?file=src/App.vue)

I only tested the component usage for now since I migrated from vue.draggable.next, where this was possible.

**Comment by Alfred-Skyblue** [comment]
Thank you, I have fixed this issue in version 0.1.4, you can use the latest version.
