### ISSUE TITLE
Inconsistent order of items after mutating the model

### ISSUE THREAD

**Issue by ionutantohi** [Alfred-Skyblue/vue-draggable-plus#173]
This is a wired one, not sure if related to vue or this package.

Say we start with a list of 3 items. If we move the last item in the list on top (or anywhere above), and then we add a new item to the list, the new item is not appended at the end of the list.

See this: https://stackblitz.com/edit/github-b2xatc-ysbvcy?file=src%2FApp.vue

Expected: If the last item in the list is moved and new item is added to the list, the new item is the last one.

**Comment by Alfred-Skyblue** [comment]
https://vue-draggable-plus.pages.dev/en/faq/
