### ISSUE TITLE
父子级表格拖拽排序问题

### ISSUE THREAD

**Issue by lsymy** [Alfred-Skyblue/vue-draggable-plus#174]
### version：
vue-draggable-plus@0.5.3

### minimal reproduction：
https://stackblitz.com/edit/vitejs-vite-r6cgko?file=src%2FApp.vue&terminal=dev

### problem description：
1. 在未展开的情况下，拖拽key为1的行到第二行后再点击展开，key为1的行展开后跑到了表格末尾。
2. 展开key=1的行后进行拖拽排序，目的为交换key=1、2的位置，此时有两个地方可以插入，一个是key=1-3下方（成功交换位置，但实际上应该不触发？），一个是key=2下方（交换位置失败）

![image](https://github.com/user-attachments/assets/9bef4b1d-3569-4a8f-b583-247213b13c6a)

**Comment by Luzy2019** [comment]
https://stackblitz.com/edit/vitejs-vite-cy7jov?file=src%2FApp.vue&terminal=dev

**Comment by lsymy** [comment]
嵌套写法应该是可以的，然后我试了下把target去掉，然后把template标签去掉之后没有问题了，感谢你的回复！
