### ISSUE TITLE
[Bug Report]双向列表拖拽+指定目标容器时(容器为组件时)，最后一个元素拖拽不消失

### ISSUE THREAD

**Issue by tangjian1891** [Alfred-Skyblue/vue-draggable-plus#18]
https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleFwiIHN0eWxlPVwiZGlzcGxheTogZmxleFwiPlxuICAgIDxWdWVEcmFnZ2FibGVcbiAgICAgIGNsYXNzPVwiZmxleCBmbGV4LWNvbCBnYXAtMiBwLTQgdy0zMDBweCBoLTMwMHB4IG0tYXV0byBiZy1ncmF5LTUwMC81IHJvdW5kZWQgb3ZlcmZsb3ctYXV0b1wiXG4gICAgICB2LW1vZGVsPVwibGlzdDFcIlxuICAgICAgYW5pbWF0aW9uPVwiMTUwXCJcbiAgICAgIGdob3N0Q2xhc3M9XCJnaG9zdFwiXG4gICAgICBncm91cD1cInBlb3BsZVwiXG4gICAgICBAdXBkYXRlPVwib25VcGRhdGVcIlxuICAgICAgQGFkZD1cIm9uQWRkXCJcbiAgICAgIEByZW1vdmU9XCJyZW1vdmVcIlxuICAgICAgc3R5bGU9XCJtYXJnaW4tcmlnaHQ6IDUwcHhcIlxuICAgICAgdGFyZ2V0PVwiLndyYXBcIlxuICAgID5cbiAgICAgIDxlbC1yb3cgY2xhc3M9XCJ3cmFwXCI+XG4gICAgICAgIDxlbC1jb2wgdi1mb3I9XCJpdGVtIGluIGxpc3QxXCIgOmtleT1cIml0ZW0uaWRcIiBjbGFzcz1cImN1cnNvci1tb3ZlIGgtMzAgYmctZ3JheS01MDAvNSByb3VuZGVkIHAtM1wiPlxuICAgICAgICAgIHt7IGl0ZW0ubmFtZSB9fVxuICAgICAgICA8L2VsLWNvbD5cbiAgICAgIDwvZWwtcm93PlxuICAgIDwvVnVlRHJhZ2dhYmxlPlxuICAgIDxWdWVEcmFnZ2FibGVcbiAgICAgIGNsYXNzPVwiZmxleCBmbGV4LWNvbCBnYXAtMiBwLTQgdy0zMDBweCBoLTMwMHB4IG0tYXV0byBiZy1ncmF5LTUwMC81IHJvdW5kZWQgb3ZlcmZsb3ctYXV0b1wiXG4gICAgICB2LW1vZGVsPVwibGlzdDJcIlxuICAgICAgYW5pbWF0aW9uPVwiMTUwXCJcbiAgICAgIGdyb3VwPVwicGVvcGxlXCJcbiAgICAgIGdob3N0Q2xhc3M9XCJnaG9zdFwiXG4gICAgICBAdXBkYXRlPVwib25VcGRhdGVcIlxuICAgICAgQGFkZD1cIm9uQWRkXCJcbiAgICAgIEByZW1vdmU9XCJyZW1vdmVcIlxuICAgICAgdGFyZ2V0PVwiLnF3ZXJcIlxuICAgID5cbiAgICAgIDxkaXYgY2xhc3M9XCJxd2VyXCI+XG4gICAgICAgIDxkaXYgdi1mb3I9XCJpdGVtIGluIGxpc3QyXCIgOmtleT1cIml0ZW0uaWRcIiBjbGFzcz1cImN1cnNvci1tb3ZlIGgtMzAgYmctZ3JheS01MDAvNSByb3VuZGVkIHAtM1wiPlxuICAgICAgICAgIHt7IGl0ZW0ubmFtZSB9fVxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZGl2PlxuICAgIDwvVnVlRHJhZ2dhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tIFwidnVlXCI7XG5pbXBvcnQgeyBWdWVEcmFnZ2FibGUgfSBmcm9tIFwidnVlLWRyYWdnYWJsZS1wbHVzXCI7XG5pbXBvcnQge0VsUm93LEVsQ29sfSBmcm9tIFwiZWxlbWVudC1wbHVzXCJcbmNvbnN0IGxpc3QxID0gcmVmKFtcbiAge1xuICAgIG5hbWU6IFwiSm9hb1wiLFxuICAgIGlkOiBcIjFcIixcbiAgfSxcbiAge1xuICAgIG5hbWU6IFwiSmVhblwiLFxuICAgIGlkOiBcIjJcIixcbiAgfSxcbiAge1xuICAgIG5hbWU6IFwiSm9oYW5uYVwiLFxuICAgIGlkOiBcIjNcIixcbiAgfSxcbiAge1xuICAgIG5hbWU6IFwiSnVhblwiLFxuICAgIGlkOiBcIjRcIixcbiAgfSxcbl0pO1xuY29uc3QgbGlzdDIgPSByZWYoXG4gIGxpc3QxLnZhbHVlLm1hcCgoaXRlbSkgPT4gKHtcbiAgICBuYW1lOiBgJHtpdGVtLm5hbWV9LTJgLFxuICAgIGlkOiBgJHtpdGVtLmlkfS0yYCxcbiAgfSkpXG4pO1xuZnVuY3Rpb24gb25VcGRhdGUoKSB7XG4gIGNvbnNvbGUubG9nKFwidXBkYXRlXCIpO1xufVxuZnVuY3Rpb24gb25BZGQoKSB7XG4gIGNvbnNvbGUubG9nKFwiYWRkXCIpO1xufVxuZnVuY3Rpb24gcmVtb3ZlKCkge1xuICBjb25zb2xlLmxvZyhcInJlbW92ZVwiKTtcbn1cbjwvc2NyaXB0PlxuPHN0eWxlPjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWUtZHJhZ2dhYmxlLXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL3Z1ZS1kcmFnZ2FibGUtcGx1c0AwLjEuNS9kaXN0L3Z1ZS1kcmFnZ2FibGUtcGx1cy5qc1wiXG4gIH1cbn0iLCJfbyI6e319

在线案例,如下图
![image](https://user-images.githubusercontent.com/39407722/236251019-61c7324f-f91d-4167-b241-e35f6b3278b7.png)

**Comment by Alfred-Skyblue** [comment]
I have fixed this bug, you can install version 0.2.0-beta.1 using.

**Comment by tangjian1891** [comment]
> Thank you. I have fixed this bug, you can install version 0.2.0-beta.1 using.

Thank you，Nice lib for drag .
