### ISSUE TITLE
我想请问一下作者，我看到这个组件好像只能在一个列表里面排序？可以在一个类似的画布里面自由排列吗？

### ISSUE THREAD

**Issue by whr2349** [Alfred-Skyblue/vue-draggable-plus#187]
我想请问一下作者，我看到这个组件好像只能在一个列表里面排序？可以在一个类似的画布里面自由排列吗？
只能在一个div这种类似的容器里面排序，感觉这个组件的重点是对一个列表进行排序，而不是自由的拖拽？

**Comment by Alfred-Skyblue** [comment]
不可以哈，画布的话就是乱序的了，这个是排序用的
