### ISSUE TITLE
VueDraggable的子节点是VueDraggable和普通节点混合时，会有BUG

### ISSUE THREAD

**Issue by jide1022** [Alfred-Skyblue/vue-draggable-plus#188]
复现链接：
https://stackblitz.com/edit/vitejs-vite-voaz9z?file=src%2FApp.vue,package.json&terminal=dev

复现步骤：
将黄色节点拖到绿色框内即可

**Comment by Alfred-Skyblue** [comment]
template的问题，把v-for的元素改成div就可以了

**Comment by jide1022** [comment]
不使用template元素使用其组件元素也会有类似的问题，如果包一层DIV确实可以解决，但是有的业务场景下需求导致不能多嵌套一层DIV

**Comment by Alfred-Skyblue** [comment]
你可以尝试嵌套一个span，使用组件元素时，必须根元素不能有多个
