### ISSUE TITLE
拖拽完成后元素样式不跟随

### ISSUE THREAD

**Issue by itliujia** [Alfred-Skyblue/vue-draggable-plus#199]
https://github.com/user-attachments/assets/c1f031c5-55d3-4c1b-b51f-4c69a44c3d8b

配置都是这样的

```vue
<vuedraggable
:list="list"
:force-fallback="true"
:animation="300"
handle=".drag-icon"
>
</vuedraggable>

**Comment by rysinal** [comment]
@itliujia 请问解决了吗

**Comment by itliujia** [comment]
> @itliujia 请问解决了吗

没有的呢，最后用的  [vuedraggable](https://github.com/SortableJS/vue.draggable.next)

**Comment by rysinal** [comment]
> <vuedraggable :list="list" :force-fallback="true" :animation="300" handle=".drag-icon"
> 
> > 
> 
> 可以提供子元素代码吗？或者给个复现也可以，盲猜用了key=index

force-fallback 有效了 感谢

**Comment by itliujia** [comment]
> <vuedraggable :list="list" :force-fallback="true" :animation="300" handle=".drag-icon"
> 
> > 
> 
> 可以提供子元素代码吗？或者给个复现也可以，盲猜用了key=index

确实我用了 `force-fallback` 就可以了，感谢感谢😂
