### ISSUE TITLE
can not use in tsx by vue3

### ISSUE THREAD

**Issue by superermiao** [Alfred-Skyblue/vue-draggable-plus#20]
<img width="791" alt="image" src="https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/24588825/57ddb2b6-1429-432d-8f3f-876bda898387">
I cant't use v-model and handle props 
<img width="848" alt="image" src="https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/24588825/719ba648-6f74-4478-a1e0-74c0a2999c16">
please check props type

**Comment by Alfred-Skyblue** [comment]
This is a problem with ts checking, please try using useDraggable.
