### ISSUE TITLE
当只进行拖拽但不改变原顺序时，追加新的数据不在最后面

### ISSUE THREAD

**Issue by daifiyum** [Alfred-Skyblue/vue-draggable-plus#202]
详情请看图：
![PixPin_2024-10-14_23-47-13](https://github.com/user-attachments/assets/d1621bec-7517-40b4-8ef7-103ad02c9c78)
复现地址：https://vue-draggable-plus.pages.dev/en/demo/handle/#component-usage

**Comment by Alfred-Skyblue** [comment]
[demo](https://play.vuejs.org/#eNp9VH9P2zAQ/Sq3aFKKBgkF9k9XENuEtCHth8ak/bFMwo2vrSE5e7ZTiqp+953jNG3RoFIt++7Z793zOavkvTHZosFklIxdaZXx4NA35qIgVRttPazA4hTWMLW6hpShaZ+64UFMKuxyrlveuS1kBZq+6IY8yr0z3hVUanIeajeD80AxSD9hVWn4pW0lX6UHBW0gleIhYn4XBLAKAwCJGkeQXmuhh+lhjCnJkSHTA6zb0BMsCjrZw548j9VzQSRO9+Cnz8MbQWd72LOILehPW8u0odIrTSCkHBzE3V19SDM/5wpDodlCVA1mXewNDANuJ2EaNx/sUd8Gani9ilvWtzsabrfRVgsLYT0F9XcyYCXnF1EM4UN/owOpy6ZG8tnfBu3jDVZYem0HacaSvVCENj043Fgg+LZFqG0Ew+Pjjl/TFckBdpWGn8RJM5uhjWsW0ini/ziPzcdtxwuPtamER14BjCeN92zbZVmp8v68SNi/IrngcZzHVIRJtYCyEs4xpBfJwMi2l1ZMUCSwOJpq2y1BUesyh0f3+NhFMxWoNvpXK2iDwXZYt/r54JxPjgq62Tjf0c9L5x+rMM1antaNibYSLbtlluB0pSQ3t+QnAVALO1N05LUJXpplGzRcrKJZH2FqNqw9NjlM4ks7qoXJ7pwmfsktB1fQJlyRjDZ3UCTbNxrCRTL33rhRnpeSeLfESi1sRuhzMnW+BV8Os+Hb7DR/g46d6/p6zeTesddTNXtCXeraqArtNxPaYl+C4Ff+cN3GvG2waxfeM8fy/j/xO7eMWr9bdGgXWCR9zrNdyJcW0lc3X3HJ8z5Za9lUjH4h+QPZ/iZojLAPDUmWvYNr1X5uneQr+Omulh7JbYoKQrdfhCLhT9vHF0rfyj3NznoX1/8AU/jM1g==)

It seems to be an issue with sortablejs, currently working on debugging it.

**Comment by daifiyum** [comment]
> [demo](https://play.vuejs.org/#eNp9VH9P2zAQ/Sq3aFKKBgkF9k9XENuEtCHth8ak/bFMwo2vrSE5e7ZTiqp+953jNG3RoFIt++7Z793zOavkvTHZosFklIxdaZXx4NA35qIgVRttPazA4hTWMLW6hpShaZ+64UFMKuxyrlveuS1kBZq+6IY8yr0z3hVUanIeajeD80AxSD9hVWn4pW0lX6UHBW0gleIhYn4XBLAKAwCJGkeQXmuhh+lhjCnJkSHTA6zb0BMsCjrZw548j9VzQSRO9+Cnz8MbQWd72LOILehPW8u0odIrTSCkHBzE3V19SDM/5wpDodlCVA1mXewNDANuJ2EaNx/sUd8Gani9ilvWtzsabrfRVgsLYT0F9XcyYCXnF1EM4UN/owOpy6ZG8tnfBu3jDVZYem0HacaSvVCENj043Fgg+LZFqG0Ew+Pjjl/TFckBdpWGn8RJM5uhjWsW0ini/ziPzcdtxwuPtamER14BjCeN92zbZVmp8v68SNi/IrngcZzHVIRJtYCyEs4xpBfJwMi2l1ZMUCSwOJpq2y1BUesyh0f3+NhFMxWoNvpXK2iDwXZYt/r54JxPjgq62Tjf0c9L5x+rMM1antaNibYSLbtlluB0pSQ3t+QnAVALO1N05LUJXpplGzRcrKJZH2FqNqw9NjlM4ks7qoXJ7pwmfsktB1fQJlyRjDZ3UCTbNxrCRTL33rhRnpeSeLfESi1sRuhzMnW+BV8Os+Hb7DR/g46d6/p6zeTesddTNXtCXeraqArtNxPaYl+C4Ff+cN3GvG2waxfeM8fy/j/xO7eMWr9bdGgXWCR9zrNdyJcW0lc3X3HJ8z5Za9lUjH4h+QPZ/iZojLAPDUmWvYNr1X5uneQr+Omulh7JbYoKQrdfhCLhT9vHF0rfyj3NznoX1/8AU/jM1g==)
> 
> It seems to be an issue with sortablejs, currently working on debugging it.

[vue.draggable.next](https://sortablejs.github.io/vue.draggable.next/#/simple) has resolved this issue; you might want to look into it.

**Comment by Alfred-Skyblue** [comment]
> [vue.draggable.next](https://sortablejs.github.io/vue.draggable.next/#/simple) has resolved this issue; you might want to look into it.[vue.draggable.next](https://sortablejs.github.io/vue.draggable.next/#/simple) 解决了这个问题;你可能想研究一下。

Does not work with the latest version of vue, where the text node is not included in `childNodes`

**Comment by daifiyum** [comment]
Thank you for the fix
