### ISSUE TITLE
当拖拽容器重叠时，拖拽元素会疯狂抽搐

### ISSUE THREAD

**Issue by iwengx** [Alfred-Skyblue/vue-draggable-plus#215]
👋作者你好，我最近在使用该库的过程中遇到了一个问题。

基本介绍：当 容器B 通过定位的方式与 容器A 重叠时，拖拽元素无法精准的进行定位，但是当 容器A 中存在了至少一个拖拽元素时，则不会出现该问题。

版本：`Vue 3.5.13` `vue-draggable-plus 0.6.0`

复现链接：[codesandbox](https://codesandbox.io/p/sandbox/trusting-star-fcrm5s?workspaceId=af044775-64e3-4997-89ec-3767a98cb6d4)

复现视频：

https://github.com/user-attachments/assets/eae23d18-2af2-4202-9c85-50b52309d8e1

**Comment by YoungDan-hero** [comment]
可以设置 :emptyInsertThreshold="0" 来解决这个问题

**Comment by iwengx** [comment]
> 可以设置 :emptyInsertThreshold="0" 来解决这个问题

可以的，谢谢好兄弟
