### ISSUE TITLE
非常严重的BUG，快速拖动会迟滞，导致无法使用

### ISSUE THREAD

**Issue by 1340145680** [Alfred-Skyblue/vue-draggable-plus#22]
我试了好多个模块都有这个问题

https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/91125707/1667ef51-9318-4a4b-a252-0f70a64d75c2

**Comment by 1340145680** [comment]
只会在edge浏览器出现

**Comment by Alfred-Skyblue** [comment]
非常抱歉，您的视频我打不开，可以提供在线使用方式吗？

**Comment by 1340145680** [comment]
> 

在edge浏览器中打开你们的示例网站https://alfred-skyblue.github.io/vue-draggable-plus/demo/basic/，随便选择一个组件拖动，按住组件，一直在列表里面上下滑动不要放开，过了几秒之后他的动画反应就会变得很慢

**Comment by 1340145680** [comment]
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/91125707/426c559f-5f80-44e9-8763-48cee54141ee)
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/91125707/f166491e-d8d5-4f1c-b8c9-1062ce48f1cf)
控制台性能测试配置文件

**Comment by 1340145680** [comment]
[Profile-20230525T093657.zip](https://github.com/Alfred-Skyblue/vue-draggable-plus/files/11560384/Profile-20230525T093657.zip)

**Comment by RJQingHuan** [comment]
关闭效率模式就不会出现这个问题了
