### ISSUE TITLE
为什么我复制示例过来无法进行拖动

### ISSUE THREAD

**Issue by moom-en** [Alfred-Skyblue/vue-draggable-plus#222]
复制任何一个示例过来都无法拖动，但是start、end事件可以触发，update不触发，我用的是vue 3.5.13、vue-draggable-plus 0.6.0，拖动也不会报任何错误，是不是还需要其他依赖之类的呢
![image](https://github.com/user-attachments/assets/985ede8e-4213-4cfe-b238-6f073d7968f8)
![image](https://github.com/user-attachments/assets/5a07116a-0d03-4105-8dda-e213736b0fe6)

**Comment by tjlizz** [comment]
加上 

` class="cursor-move h-30 bg-gray-500/5 rounded p-3"`

**Comment by moom-en** [comment]
> 加上
> 
> ` class="cursor-move h-30 bg-gray-500/5 rounded p-3"`

还是不行呢。。

**Comment by moom-en** [comment]
> 加上
> 
> ` class="cursor-move h-30 bg-gray-500/5 rounded p-3"`

我把几个demo都复制过来，全都无法拖动

**Comment by tjlizz** [comment]
```
  <VueDraggable
            ref="el"
            v-model="list"
            :animation="150"
            ghostClass="ghost"
            class="flex flex-col gap-2 p-4 w-300px h-300px m-auto bg-gray-500/5 rounded"
            @start="onStart"
            @update="onUpdate"
            @end="onEnd"
          >
            <div
              v-for="item in list"
              :key="item.id"
              class="cursor-move h-30 bg-gray-500/5 rounded p-3"
            >
              {{ item.name }}
            </div>
          </VueDraggable>
```

我这个可以

**Comment by moom-en** [comment]
> ```
> 
>   const list = ref([
>     { id: 1, name: '项1' },
>     { id: 2, name: '项2' },
>     { id: 3, name: '项3' },
>     { id: 4, name: '项4' },
>   ]);
> 
>   const el = ref<UseDraggableReturn>();
>   const onStart = (e: DraggableEvent) => {
>     console.log('start', e);
>   };
> 
>   const onEnd = (e: DraggableEvent) => {
>     console.log('onEnd', e);
>     console.log(list);
>   };
> 
>   const onUpdate = () => {
>     console.log('update');
>   };
> 
> 
>   <VueDraggable
>             ref="el"
>             v-model="list"
>             :animation="150"
>             ghostClass="ghost"
>             class="flex flex-col gap-2 p-4 w-300px h-300px m-auto bg-gray-500/5 rounded"
>             @start="onStart"
>             @update="onUpdate"
>             @end="onEnd"
>           >
>             <div
>               v-for="item in list"
>               :key="item.id"
>               class="cursor-move h-30 bg-gray-500/5 rounded p-3"
>             >
>               {{ item.name }}
>             </div>
>           </VueDraggable>
> ```
> 
> 我这个可以

你这个我复制过来css有样式，但还是无法拖动
