### ISSUE TITLE
浏览器下正常工作，但是在tauri下无法拖动

### ISSUE THREAD

**Issue by moom-en** [Alfred-Skyblue/vue-draggable-plus#223]
浏览器下正常工作，但是在tauri下无法拖动，也没有任何错误

**Comment by xwzkj** [comment]
我也遇见了这个问题，需要在创建window的时候禁用这个

                        dragDropEnabled: false, // 这样才可以启用html5拖拽

**Comment by moom-en** [comment]
> 我也遇见了这个问题，需要在创建window的时候禁用这个
> 
> ```
>                     dragDropEnabled: false, // 这样才可以启用html5拖拽
> ```

谢谢你，我已经解决了
