### ISSUE TITLE
没有类型提示

### ISSUE THREAD

**Issue by heroboy** [Alfred-Skyblue/vue-draggable-plus#30]
`vue-demi`模块在devDependencies中，而生成的component.d.ts中`import('vue-demi')`，导致最终`VueDraggable`的类型是`any`

**Comment by heroboy** [comment]
> 我也遇到了，请问怎么解决 @heroboy
> 
> > `vue-demi`模块在devDependencies中，而生成的component.d.ts中`import('vue-demi')`，导致最终`VueDraggable`的类型是`any`

`npm i vue-demi`

**Comment by Alfred-Skyblue** [comment]
Replaced `vue-demi` with `vue`, thanks.

```bash
npm i vue-draggable-plus@0.2.3
```
