### ISSUE TITLE
Is it possible to validate whether or not you can drag?

### ISSUE THREAD

**Issue by luisrossi** [Alfred-Skyblue/vue-draggable-plus#32]
Is there a way for me to validate in a method whether or not an element can be dragged to another parent component?
In summary my use case is:
I have 2 lists and some specific list items can be dragged to another list and some not

Example:
```js
if (event.clone.className === "fixed" && event.to.id === "availableFields") {
```
would be equivalent to prop :move="function" of vuedraggable

**Comment by Alfred-Skyblue** [comment]
`onMove` or  `@move` return false.


```vue
 <VueDraggable
      v-model="list1"
      :onMove="(e) => false"
    >
 </VueDraggable>
```

or

```vue
 <VueDraggable
      v-model="list1"
      @move="(e) => false"
    >
 </VueDraggable>
```

**Comment by luisrossi** [comment]
Move within the component itself for sorting. That yes, today is already validated.
But when it's from one component to the other, the move is not activated, but the remove/add and I can't cancel it.

I had to do the treatment by hand.
