### ISSUE TITLE
无法和ts一起使用

### ISSUE THREAD

**Issue by 634323580** [Alfred-Skyblue/vue-draggable-plus#33]
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/12928893/8b09fde0-4569-4e28-90b5-9644ba047b41)

**Comment by Alfred-Skyblue** [comment]
Install version 0.2.4, already supported

```bash
npm i vue-draggable-plus@0.2.4
```

**Comment by Alfred-Skyblue** [comment]
Please upgrade the version to 0.2.4.

```bash
npm i vue-draggable-plus@0.2.4
```
