### ISSUE TITLE
在火狐浏览器中拖拽完成后会打开搜索页面

### ISSUE THREAD

**Issue by Pandaft** [Alfred-Skyblue/vue-draggable-plus#35]
见动图：

![gif](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/80463781/b1e95164-1ee9-4573-b18c-35b386375775)

在 Chrome 、 Edge 浏览器上没有该问题。

**Comment by Alfred-Skyblue** [comment]
在火狐浏览器中可以使用以下方式阻止打开搜索页的问题

```ts
document.body.ondrop = function (event) {
  event.preventDefault()
  event.stopPropagation()
}
```

建议把这段代码添加到全局

**Comment by Pandaft** [comment]
实测有效，感谢！
