### ISSUE TITLE
feature request: add example Nested draggable

### ISSUE THREAD

**Issue by reslear** [Alfred-Skyblue/vue-draggable-plus#4]

**Comment by AlexandreAtErgosign** [comment]
It can be the same as https://sortablejs.github.io/vue.draggable.next/#/nested-example

**Comment by Alfred-Skyblue** [comment]
I have added a nested example in the document, you can check it out, thank you for your suggestion.

**Comment by TomasSestak** [comment]
> I have added a nested example in the document, you can check it out, thank you for your suggestion.

In what document exactly? Cant find it.

**Comment by Evenerik** [comment]
> > I have added a nested example in the document, you can check it out, thank you for your suggestion.
> 
> In what document exactly? Cant find it.

For anyone else struggling to find the example in the docs, it's here:
https://github.com/Alfred-Skyblue/vue-draggable-plus/blob/main/src/__docs__/nested/NestedComponent.vue

Was exactly what I was looking for when I was stuck trying to sort nested sets
