### ISSUE TITLE
View not updated

### ISSUE THREAD

**Issue by Huangjiafua** [Alfred-Skyblue/vue-draggable-plus#47]
When I package the latest version with "^", the data is successfully updated after dragging, but the view is not updated.

**Comment by Alfred-Skyblue** [comment]
Can the smallest replica be provided? Because the official demo can be dragged and updated

**Comment by Huangjiafua** [comment]
> Can the smallest replica be provided? Because the official demo can be dragged and updated.
Currently, our app is on the shopify platform and is not available. Our native debugging is fine, when repackaging with the latest version, there will be problems, and when we lock version 0.2.1, it will be fine.
