### ISSUE TITLE
Drag and drop report JSON conversion error in production environment

### ISSUE THREAD

**Issue by wenyongda** [Alfred-Skyblue/vue-draggable-plus#48]
There is no problem with using it in the development environment.
But I will report Error when I pack and deploy to the production environment.
Converting circular structure to JSON
    --> starting at object with constructor 'Object'
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/68416083/1e8b31d2-170a-4bab-8124-10852accfed4)
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/68416083/8e3b5192-b50c-4e47-a05e-ea7576e89c66)
But the function is good.

**Comment by Alfred-Skyblue** [comment]
Due to the fact that your object structure does not support JSON serialization, you can pass a custom cloning function to implement your own cloning functionality.

```ts
import { cloneDeep } from 'lodash-es'

useDraggable(el, list, {
  clone: cloneDeep
})
```

**Comment by luveqz** [comment]
In my case, I had stored my **`list`** on a Pinia store, so it was enough for me to use [toRaw()](https://vuejs.org/api/reactivity-advanced.html#toraw):

```js
import { toRaw } from 'vue'

useDraggable(el, list, {
  clone: toRaw
})
```
