### ISSUE TITLE
swiper+draggable

### ISSUE THREAD

**Issue by lzdml** [Alfred-Skyblue/vue-draggable-plus#49]
<img width="947" alt="image" src="https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/137750167/da0f98f7-55a2-40ac-8cf2-9669243124eb">

disabled如何根据icons[index]遍历出来的item内的属性来判断是否可以拖拽?

**Comment by Alfred-Skyblue** [comment]
```vue
<draggable
  :filter=".ignore-element"
 v-model="list"
>
<div v-for="(item, index) in list" :class="{'.ignore-element':index%2===0}">

<div>

</draggable>

```

**Comment by lzdml** [comment]
感谢感谢, 感觉文档还可以完善一点, 每一个属性最起码案例里面有是最好的

**Comment by Alfred-Skyblue** [comment]
> 感谢感谢, 感觉文档还可以完善一点, 每一个属性最起码案例里面有是最好的

好的，回头会完善一下，谢谢你的提议

**Comment by Alfred-Skyblue** [comment]
包含块的问题

**Comment by lzdml** [comment]
有办法不让往前挤吗, 或者有对应的拖拽文章推荐吗

**Comment by Alfred-Skyblue** [comment]
如果你没有双向绑定元素，当拖拽开始时，你复制一个相同的元素放到原位置将它设置为透明，就可以了，如果你对元素进行了数据绑定，你可以对拖拽源数据追加一个数组项，来保持原有的结构
