### ISSUE TITLE
Vitepress dependency outdated

### ISSUE THREAD

**Issue by vchernin** [Alfred-Skyblue/vue-draggable-plus#50]
I noticed when loading a page like https://alfred-skyblue.github.io/vue-draggable-plus/en/ the page does not load properly, even though that is the correct url, which can you get to by switching to English using the language switcher.

I was able to resolve the issue locally by simply upgrading vitepress to `1.0.0-rc.20` and vue to `3.3.4`. However, the website seems a bit broken, the language switcher at the top right no longer exists, seemingly because the vitepress i18n api changed: https://vitepress.dev/guide/i18n#internationalization. I could not fix those because vitepress was still sort of using an older version, since `@ruabick/md-demo-plugins` also depends on an older vitepress version: https://github.com/dewfall123/ruabick/issues/36.

**Comment by Alfred-Skyblue** [comment]
https://github.com/Alfred-Skyblue/vue-draggable-plus/issues/59#issuecomment-1822330517
