### ISSUE TITLE
feat

### ISSUE THREAD

**Issue by MinMr** [Alfred-Skyblue/vue-draggable-plus#55]
大佬，官网能出个简单拖拽的demo吗，不是那种交换顺序的拖拽，就是简单纯拖拽单个物体

**Comment by Alfred-Skyblue** [comment]
Do you mean you want a feature to manually drag and modify the position of a DOM element? If so, you can use `useDraggable` from VueUse to achieve this. You can find more information about it [here](https://vueuse.org/core/useDraggable/).
