### ISSUE TITLE
English version of docs doesn't work on GH Pages

### ISSUE THREAD

**Issue by Igloczek** [Alfred-Skyblue/vue-draggable-plus#59]
English version of docs doesn't work on GH Pages. After adding `/en/` to URL, CSS and JS are not properly loaded, because paths are like `/vue-draggable-plus/en/assets/style.bdd25d48.css` instead `/vue-draggable-plus/assets/style.bdd25d48.css`

**Comment by Alfred-Skyblue** [comment]
The problem caused by vitepress, I will solve it as soon as possible, thank you.
