### ISSUE TITLE
feature Request: Make compatible with vue-virtual-scroller

### ISSUE THREAD

**Issue by theSilverFisch** [Alfred-Skyblue/vue-draggable-plus#6]
I'm currently trying to combine the [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller/tree/master/packages/vue-virtual-scroller) with draggablePlus. Apparently the drag items can not be obtained if they are rendered within the dynamic scrollerItem. 
My current setup is as follows:

```
<DynamicScroller page-mode class="scroller" :items="vScrollItems"
  :min-item-size="ticketHeight" key-field="docUUID"
  v-draggable="[vScrollItems, draggableDirectiveConf]">
  <template v-slot="{ item, index, active }">
    <DynamicScrollerItem :item="item" :active="active" :data-index="index" class="ticketDrag">
      <ticket-item :key="item.docUUID"
        :ticketItemId="item.docUUID" />
    </DynamicScrollerItem>
  </template>
</DynamicScroller>
```

```
const vScrollItems = [
  {
    docUUID:'77d8f970-bace-4d34-bcc0-6c932242e0ae'
  },
  {
    docUUID: '76d8f970-bace-4d34-bcc0-6c932242e0ae'
  },
  {
    docUUID: '77d8f970-bace-4d34-bcc0-9c932242e0ae'
  }
];
const ticketDrag = {
  name: 'ticketSort',
  pull: ['ticketSort'],
  put: ['ticketSort']
};
const draggableDirectiveConf = {
  animation: 150,
  target: '.ticketDrag',
  group: ticketDrag,
  handle: ".v-card-item__prepend"
}
```

whilst the ticket-item is a seperate component containing a [vuetify card](https://vuetifyjs.com/en/components/cards/).
No Matter if I use target or el or place the class on the ticketItem or the scrollerItem, it always selects all items within the dynamicScroller for dragging, not each individually. Or am I doing something wrong here?

Regards

**Comment by Alfred-Skyblue** [comment]
Sorry, the directive cannot use the target container, you can try to use the target container in the component

**Comment by Alfred-Skyblue** [comment]
```vue
<template>
  <section>
    <div>
      <VueDraggable v-model="list" animation="150" target=".el-table">
        <ElTable :list="list"></ElTable>
      </VueDraggable>
    </div>
    <div class="flex justify-between">
      <preview-list :list="list" />
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { VueDraggable } from 'vue-draggable-plus'
import ElTable from './ElTable.vue'

const list = ref([
  {
    name: 'Joao',
    id: '1'
  },
  {
    name: 'Jean',
    id: '2'
  },
  {
    name: 'Johanna',
    id: '3'
  },
  {
    name: 'Juan',
    id: '4'
  }
])
</script>


```

**Comment by theSilverFisch** [comment]
> ```
> <template>
>   <section>
>     <div>
>       <VueDraggable v-model="list" animation="150" target=".el-table">
>         <ElTable :list="list"></ElTable>
>       </VueDraggable>
>     </div>
>     <div class="flex justify-between">
>       <preview-list :list="list" />
>     </div>
>   </section>
> </template>
> 
> <script setup lang="ts">
> import { ref } from 'vue'
> import { VueDraggable } from 'vue-draggable-plus'
> import ElTable from './ElTable.vue'
> 
> const list = ref([
>   {
>     name: 'Joao',
>     id: '1'
>   },
>   {
>     name: 'Jean',
>     id: '2'
>   },
>   {
>     name: 'Johanna',
>     id: '3'
>   },
>   {
>     name: 'Juan',
>     id: '4'
>   }
> ])
> </script>
> ```

so you say 
 ```
.el-table
 ```
should be a class within the component
 ```
 <ElTable :list="list"></ElTable>
 ```

sadly this has the same result. Clicking the handle of one item lets me drag the whole column, not just a single item entry

**Comment by Alfred-Skyblue** [comment]
What you need to do is to find a way to obtain the parent element of the dragged item, and pass it to useDraggable. You can refer to the [demo](https://stackblitz.com/edit/vitejs-vite-rdvmys?file=src/App.vue) for guidance.

https://stackblitz.com/edit/vitejs-vite-rdvmys?file=src/App.vue

**Comment by 204065248** [comment]
> What you need to do is to find a way to obtain the parent element of the dragged item, and pass it to useDraggable. You can refer to the [demo](https://stackblitz.com/edit/vitejs-vite-rdvmys?file=src/App.vue) for guidance.你需要做的是找到一种方法来获取拖动项的父元素，并将其传递给 useDraggable。您可以参考演示以获取指导。
> 
> https://stackblitz.com/edit/vitejs-vite-rdvmys?file=src/App.vue

这个拖拽库不支持虚拟列表的

**Comment by felixgabler** [comment]
I am using [`vue-virtual-scroller`](https://github.com/Akryum/vue-virtual-scroller/tree/master) with this code (simplified):

```vue
<script setup lang="ts">
import { useDraggable, type SortableEvent } from 'vue-draggable-plus';
import { RecycleScroller } from 'vue-virtual-scroller';
import 'vue-virtual-scroller/dist/vue-virtual-scroller.css';
// ...

const scrollerEl = ref<ComponentPublicInstance<typeof RecycleScroller>>();
const listEl = computed<HTMLElement | undefined>(
    () => scrollerEl.value?.$el.querySelector('.vue-recycle-scroller__item-wrapper') ?? undefined,
);

useDraggable(
    listEl,
    items,
);
</script>

<template>
    <RecycleScroller
        ref="scrollerEl"
        v-slot="{ item }"
        :items="items"
        :item-size="30">
        <div>
            {{ item }}
        </div>
    </RecycleScroller>
</template>
```

Unfortunately, this does not work and the item immediately jumps back when dragging. @Alfred-Skyblue do you have any idea why this could be?

**Comment by FriAfternoon** [comment]
> I found it works with the less sophisticated [`useVirtualList`](https://vueuse.org/core/useVirtualList/) provided by `vueuse`.

@felixgabler Sorry for the bother, is there any workaround example here? It would be appreciated ❤️

**Comment by felixgabler** [comment]
> > I found it works with the less sophisticated [`useVirtualList`](https://vueuse.org/core/useVirtualList/) provided by `vueuse`.
> 
> @felixgabler Sorry for the bother, is there any workaround example here? It would be appreciated ❤️

Sure, I use it like this:

```vue
<script setup lang="ts">
import { useVirtualList } from '@vueuse/core';
import { useDraggable, type SortableEvent } from 'vue-draggable-plus';

...

const { list, containerProps, wrapperProps } = useVirtualList(items, { itemHeight: ITEM_HEIGHT });
const wrapperEl = ref<HTMLElement>();

useDraggable(
    wrapperEl,
    items,
    computed(() => ({
        fallbackOnBody: true,
        swapThreshold: 0.65,
        onEnd: handleReordered,
    })),
);
</script>

<template>
    <div v-bind="containerProps">
        <div ref="wrapperEl" v-bind="wrapperProps">
              <template v-for="item in list" :key="item.index">
                  <any element to show item />
              </template>
          </div>
    </div>
</template>
```

Hopefully this helps!
