### ISSUE TITLE
暴露出一个拖拽中经过元素的api

### ISSUE THREAD

**Issue by IT-Tagore** [Alfred-Skyblue/vue-draggable-plus#61]
例如在原生拖拽中`dragenter`进入一个同为可拖拽元素或组时,可以监听到经过的元素,即使不在自身原本的组内,SortableJS并没有暴露出来,只有在拖拽元素所处的组件才能监听到.

**Comment by lzdml** [comment]
这个自行判断一下就行吧 @IT-Tagore

**Comment by Alfred-Skyblue** [comment]
既然原生可以，那就用原生。

**Comment by IT-Tagore** [comment]
> 既然原生可以，那就用原生。

good job

**Comment by IT-Tagore** [comment]
> 这个自行判断一下就行吧 @IT-Tagore

用sortable了

**Comment by Alfred-Skyblue** [comment]
如果是同组的之间的互相拖拽，应该使用 `onAdd`

**Comment by IT-Tagore** [comment]
> 如果是同组的之间的互相拖拽，应该使用 `onAdd`

onAdd我试过，他只有在拖放组内添加新元素的时监听到，我的想法是当鼠标按下时拖拽一个有效元素那么这个元素经过有效元素或者有效放置区域时的这个过程都可以被监听到，可能这个场景不常见。我可以想想其他办法。
