### ISSUE TITLE
如何实现分组下的数据可以拖动，而分组不能拖动

### ISSUE THREAD

**Issue by busy-tester** [Alfred-Skyblue/vue-draggable-plus#64]
有个需求如下
我有好多的分组，例如下面的资讯模块、资产模块、交易模块、项目模块。每个分组下都有若干条数据，例如下面的获取数据、注册、修改、删除
因为数据比较多，所以是放在分组下面的，现在的需求是当我点击分组名称的时候，展示分组下面的数据，这时候可以拖拽分组下的数据，但是分组不能拖动
请问我该怎么做？
<img width="317" alt="image" src="https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/43669330/d5fb9ac4-8f4d-476e-82f5-b4a1c193f02f">
<img width="784" alt="image" src="https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/43669330/c1f003cb-d602-49b4-ae12-8c19fee3fbe3">

**Comment by Alfred-Skyblue** [comment]
1. 拖拽分组，将分组下的列表根元素使用 VueDraggable 组件包装
2. 使用克隆 https://alfred-skyblue.github.io/vue-draggable-plus/demo/clone/
