### ISSUE TITLE
自定义拖拽预览图

### ISSUE THREAD

**Issue by Fun005** [Alfred-Skyblue/vue-draggable-plus#66]
请问如何自定义拖拽过程中的预览图？通过chosenClass和dragClass吗，还是有其他的方案，感谢解答。

**Comment by Alfred-Skyblue** [comment]
实际上 sortablejs 只是对拖拽项进行了克隆，如果您需要改变它的样式，可以使用chosenClass和dragClass这两个选项添加自定义类名，通过类名获取到元素进行修改，或者添加自定义的样式
