### ISSUE TITLE
nested-component doesn't work

### ISSUE THREAD

**Issue by desousar** [Alfred-Skyblue/vue-draggable-plus#67]
Thanks for proposing an alternative to vuedraggable on Vue3 !

Situation: I have a card list. Some cards may contain other cards. This is the same behavior you illustrated in your demo ([https://alfred-skyblue.github.io/vue-draggable-plus/en/demo/nested/](https://alfred-skyblue.github.io/vue-draggable-plus/en/demo/nested/)).

I've reproduced the same basic example in my application, but the list isn't rendered.

VueDraggable alone works correctly, but not with nested-component

My application: Vue 3, currently in Option API (migration to composition API to come). I run it in google chrome.
"vue": "^3.3.9",
"vue-draggable-plus": "^0.3.0",

```
<VueDraggable tag="ul" v-model="lista" group="g1">
    <li v-for="el in modelValue" :key="el.name">
      <p>{{ el.name }}</p>
      <nested-component v-model="el.children" />
    </li>
  </VueDraggable>


data() {
  return {
    lista: [
        {
          name: 'item 1',
          children: [
            {
              name: 'item 2',
              children: [],
            },
          ],
        },
        {
          name: 'item 3',
          children: [
            {
              name: 'item 4',
              children: [],
            },
          ],
        },
        {
          name: 'item 5',
          children: [],
        },
      ],
  }
}
```

**Comment by Alfred-Skyblue** [comment]
Ensure there is a default height when `children.length` is 0; otherwise, the drag-and-drop may not find the target element.

**Comment by desousar** [comment]
Ok I added the class class="drag-area" to VueDraggable and I change v-model with :list 

```
<VueDraggable class="drag-area" tag="ul" :list="lista" group="g1">
  <li v-for="el in lista" :key="el.name">
    <p>{{ el.name }}</p>
    <nested-component v-model="el.children" />
  </li>
</VueDraggable>
```

I use the same data `lista`

```
.drag-area {
  min-height: 50px;
  outline: 1px dashed;
}
```

### First try with `<nested-component v-model="el.children" />`

result:
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/44868857/1f05a5f5-d6eb-4c89-a7d9-6aaad786b748)

browser inspector:
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/44868857/fb6412d4-1a93-4a04-a453-f21c7b1ff21a)

### Second try with `<nested-component :list="el.children" />`

result: GUI screenshot (same result)

browser inspector:
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/44868857/040c4df6-cb55-4280-af41-bb3e8e6a6122)


**Am I doing something wrong with the `nested-component` ?**

**Comment by Alfred-Skyblue** [comment]
This is a recursive component; if nesting is required, you need to recursively call itself.

<img width="1091" alt="image" src="https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/55641773/df98d384-3d13-4a54-aed4-50817199b182">

**Comment by desousar** [comment]
Oh.... yes..... I just didn't pay attention to the detail. 
Indeed, it works much better now!
