### ISSUE TITLE
Initiate dragging only on specific child element

### ISSUE THREAD

**Issue by MartinMalinda** [Alfred-Skyblue/vue-draggable-plus#68]
Hi! 

Thank you for this library. For optimal UX I need to initiate dragging only when a specific child button is being dragged, similarly how it's done on many other sites, for example Airtable:

<img width="168" alt="Screenshot 2023-12-08 at 17 45 59" src="https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/9468793/5c501a0e-aef5-41c1-b39a-62bc675a3ba6">

Notice the grid dot icon on the right side, the element is draggable only when held there.

Is there a way to implement this via vue draggable plus? An ideal solution for me would be to use some specific template slot, and if the template slot exists, the component would only initiate dragging on that child element.

Thanks a lot!

**Comment by Alfred-Skyblue** [comment]
To enable drag-and-drop functionality within a specific element, you should pass the `handle` attribute.


https://alfred-skyblue.github.io/vue-draggable-plus/en/demo/handle/

**Comment by MartinMalinda** [comment]
perfect, thank you!
