### ISSUE TITLE
Refactor `moveArrayElement` function 

### ISSUE THREAD

**Issue by chouchouji** [Alfred-Skyblue/vue-draggable-plus#71]
This function aims to move an element in an array from one position to another.

I have another idea to realize it.

![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/70570907/b91ae72d-c8f8-4e11-99a9-48d30c155f81)

**Comment by Alfred-Skyblue** [comment]
Firstly, thank you for your suggestions. However, the two functions you described above essentially serve different purposes. Currently, I am using a function to move an element to a target position, whereas the functionality you implemented involves swapping the positions of two elements.

```ts
const arr1 = [1, 2, 3, 4, 5]

arr1.splice(0, 0, arr1.splice(4, 1)[0])

console.log(arr1) // [5, 1, 2, 3, 4]   ✅

// ===========================

const arr2 = [1, 2, 3, 4, 5]

;[arr2[0],arr2[4]] = [arr2[4],arr2[0]]

console.log(arr2) // [5, 2, 3, 4, 1]   ❌



```

**Comment by chouchouji** [comment]
Sorry,I&nbsp;may&nbsp;misunderstand&nbsp;it,&nbsp;I&nbsp;will&nbsp;check&nbsp;it&nbsp;after&nbsp;eatting.We&nbsp;have&nbsp;community&nbsp;groups?


---Original---
From: ***@***.***&gt;
Date: Sun, Dec 10, 2023 13:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Alfred-Skyblue/vue-draggable-plus] Refactor `moveArrayElement`function  (Issue #71)




 
Firstly, thank you for your suggestions. However, the two functions you described above essentially serve different purposes. Currently, I am using a function to move an element to a target position, whereas the functionality you implemented involves swapping the positions of two elements.
 const arr1 = [1, 2, 3, 4, 5] arr1.splice(0, 0, arr1.splice(4, 1)[0]) console.log(arr1) // [5, 1, 2, 3, 4]   ✅ // =========================== const arr2 = [1, 2, 3, 4, 5] ;[arr2[0],arr2[4]] = [arr2[4],arr2[0]] console.log(arr2) // [5, 2, 3, 4, 1]   ❌ 
 
&mdash;

**Comment by Alfred-Skyblue** [comment]
I apologize, but I haven't created a community group at the moment. I have enabled [discussions](https://github.com/Alfred-Skyblue/vue-draggable-plus/discussions), and you can participate in [discussions](https://github.com/Alfred-Skyblue/vue-draggable-plus/discussions). If you are a Chinese user, you can click on '联系我' in the Chinese documentation to contact me and obtain my contact information.
