### ISSUE TITLE
跨组件 clone 会失败

### ISSUE THREAD

**Issue by top319VIP** [Alfred-Skyblue/vue-draggable-plus#73]
组件 A 列表允许 clone，拖拽克隆到组件 B后，组件 A 列表中被选中项消失了。
组件 A 配置：
<template>
<VueDraggable
      v-model="list1"
      animation="150"
      ghostClass="ghost"
      :group="{ name: 'people', pull: 'clone', put: false }"
      :clone="clone"
      :sort="false"
    >
      ……
    </VueDraggable>
</template>
<script setup>
const clone = (data) => data
</script>
组件 B 配置：
 <VueDraggable
        v-model="list"
        class="el-card__body-draggable"
        handle=".drag-handler"
        group="people"
        animation="150"
        @change="draggableChangeHandler"
>
……
</VueDraggable>

**Comment by Alfred-Skyblue** [comment]
Please refer to the [demo](https://alfred-skyblue.github.io/vue-draggable-plus/demo/custom-clone/) or provide a minimal reproducible example for troubleshooting. Without that, it's challenging to identify the issue.
