### ISSUE TITLE
How to disabled the first element from being dragged?

### ISSUE THREAD

**Issue by warmthsea** [Alfred-Skyblue/vue-draggable-plus#79]
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/45450994/5f24a1d3-dd83-490b-aa67-15c7f4b41f53)

**Comment by Aaron-zon** [comment]
给首页一个class然后设置filter属性过滤掉这个class就行，大概这么个意思
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/47178158/6e74d490-491c-47ad-abde-ebb8b5e638df)

**Comment by warmthsea** [comment]
> 给首页一个class然后设置filter属性过滤掉这个class就行，大概这么个意思
> 
> ![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/47178158/6e74d490-491c-47ad-abde-ebb8b5e638df)
> 
> 

Thanks.
