### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by bhaviljain68** [Alfred-Skyblue/vue-draggable-plus#8]
Hi, 
I was looking at your documentation and I couldn't find a guide to the API (Props the components accepts, Emitted events)
Could you please guide me?

I want to increase the area that triggers the scroll and dont want to show the ghost ... are these things possible?

**Comment by Alfred-Skyblue** [comment]
Hello, the document is fully inherited from Sortablejs. I have added the API module to the document. You can check it out. Thank you for your suggestion.

**Comment by bhaviljain68** [comment]
Hey... Thanks for the response and updating the readme... It is a big help.

I checked the API and tried To use the scrollsensitivity, but it didn't work

```
<VueDraggable
    v-model="formStructure[sectionIndex]"
    animation="150"
    ghostClass="ghost"
    chosenClass="ghost"
    dragClass="drag"
    handle=".handle"
    group="questions"
    @choose="sorting = true"
    @unchoose="sorting = false"
    :sort="true"
    :scrollSensitivity="75"
  >
```

I also tried

```
<VueDraggable
    ...
    scrollSensitivity="75"
  >
```

But neither seemed to have an effect
