### ISSUE TITLE
克隆 + 双列表拖拽，联合使用时的bug

### ISSUE THREAD

**Issue by LMchensir** [Alfred-Skyblue/vue-draggable-plus#84]
克隆 + 双列表拖拽，联合使用时的bug，相同的且顺序紧挨着的组件将第一个clone过来的组件从list2，拖入list3时，会导致list2中相同的组件消失

复现条件：
1. 克隆 + 双列表拖拽联合使用
2. 从克隆组件，clone两个相同的组件到list2中，且这两个相同的组件顺序要紧挨着
3. 将clone进list2中的两个相同组件中的第一个，必须是第一个，第二个不会出现问题，拖入list3中，就会导致list2中剩余的那个组件消失

简单录了一个操作视频，但是我不知道为什么我的视频无法在线观看，请下载后观看，谢谢
https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/51938074/d78014f4-4ed5-4c20-b6b3-90c6abb13a73

下面是完整的复现代码，只有一个代码，下载后就可以复现是使用

[cloneMultiDrag.txt](https://github.com/Alfred-Skyblue/vue-draggable-plus/files/13792374/cloneMultiDrag.txt)

![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/51938074/b064a706-0056-4f30-9fc7-f4841ec03181)

**Comment by 1340145680** [comment]
一样的问题+1，列表1还有两个元素，将一个拖到其他列表会消失
![2023-12-31_15-52-01](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/91125707/500d752d-dad4-4aea-85eb-44e3de8e9889)

**Comment by 1340145680** [comment]
> 一样的问题+1，列表1还有两个元素，将一个拖到其他列表会消失 ![2023-12-31_15-52-01](https://private-user-images.githubusercontent.com/91125707/293495485-500d752d-dad4-4aea-85eb-44e3de8e9889.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDk3NzcsIm5iZiI6MTcwNDAwOTQ3NywicGF0aCI6Ii85MTEyNTcwNy8yOTM0OTU0ODUtNTAwZDc1MmQtZGFkNC00YWVhLTg1ZWItNDRlM2RlOGU5ODg5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA3NTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTcyMGJiNDMwZTNlYzllNjg0NWNmOGM5NzQyOTYyYmM3NWM2M2VhMzdhODdkNDc2ZGNhOWRmZWJkNWY5NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPSFx1n-45s33Wczb4P83a2A1-dwM4Zukl00ZB-GOws) [ ![2023-12-31_15-52-01](https://private-user-images.githubusercontent.com/91125707/293495485-500d752d-dad4-4aea-85eb-44e3de8e9889.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDk3NzcsIm5iZiI6MTcwNDAwOTQ3NywicGF0aCI6Ii85MTEyNTcwNy8yOTM0OTU0ODUtNTAwZDc1MmQtZGFkNC00YWVhLTg1ZWItNDRlM2RlOGU5ODg5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA3NTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTcyMGJiNDMwZTNlYzllNjg0NWNmOGM5NzQyOTYyYmM3NWM2M2VhMzdhODdkNDc2ZGNhOWRmZWJkNWY5NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPSFx1n-45s33Wczb4P83a2A1-dwM4Zukl00ZB-GOws) ](https://private-user-images.githubusercontent.com/91125707/293495485-500d752d-dad4-4aea-85eb-44e3de8e9889.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDk3NzcsIm5iZiI6MTcwNDAwOTQ3NywicGF0aCI6Ii85MTEyNTcwNy8yOTM0OTU0ODUtNTAwZDc1MmQtZGFkNC00YWVhLTg1ZWItNDRlM2RlOGU5ODg5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA3NTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTcyMGJiNDMwZTNlYzllNjg0NWNmOGM5NzQyOTYyYmM3NWM2M2VhMzdhODdkNDc2ZGNhOWRmZWJkNWY5NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPSFx1n-45s33Wczb4P83a2A1-dwM4Zukl00ZB-GOws) [ ](https://private-user-images.githubusercontent.com/91125707/293495485-500d752d-dad4-4aea-85eb-44e3de8e9889.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDk3NzcsIm5iZiI6MTcwNDAwOTQ3NywicGF0aCI6Ii85MTEyNTcwNy8yOTM0OTU0ODUtNTAwZDc1MmQtZGFkNC00YWVhLTg1ZWItNDRlM2RlOGU5ODg5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA3NTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTcyMGJiNDMwZTNlYzllNjg0NWNmOGM5NzQyOTYyYmM3NWM2M2VhMzdhODdkNDc2ZGNhOWRmZWJkNWY5NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPSFx1n-45s33Wczb4P83a2A1-dwM4Zukl00ZB-GOws)

bug应该还是重绘得bug，数据是存在的但dom元素没更新，目前临时解决办法是在素昂列表上都加上@add事件，然后通过v-if强制刷新dom。
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/91125707/55882e26-d87c-4903-8c89-bd80040e78bf)
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/91125707/0fd9bf43-cd84-4126-a86a-9411d5fadbe7)

**Comment by Alfred-Skyblue** [comment]
https://alfred-skyblue.github.io/vue-draggable-plus/faq/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

Please ensure the uniqueness of the key. You should update the key in the clone option to prevent rendering errors caused by duplicate keys when dragging multiple identical elements.

```ts
useDraggable(el1, list1, {
  animation: 150,
  group: { name: 'people', pull: 'clone', put: false },
  sort: false,
  clone(item: Record<'id' | 'name', string>) {
    return {
      ...item,
      // 更新 id
      id: item.id + +new Date()
    }
  }
})
```
