### ISSUE TITLE
Drag and Drop Outside to a div

### ISSUE THREAD

**Issue by vishnug-bridge** [Alfred-Skyblue/vue-draggable-plus#88]
I am creating a Kanban board task viewer. In this kanban, I have many tasks and a date. I can drag and drop this into a group. I have a div outside of the draggable component. When I drag a task item to this div, I want to detect it. Is there any way to detect it?

This is what I am trying to achieve.

![284047603-7aebcd08-3368-4ada-9b07-2f022c5caad8](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/147032947/238176cb-c5d0-4b0b-a23f-2ea89148f615)

**Comment by Alfred-Skyblue** [comment]
Listen for the `dragenter` Event on an External div.
