### ISSUE TITLE
自定义克隆时，放置的目标顺序错误

### ISSUE THREAD

**Issue by zhifengle** [Alfred-Skyblue/vue-draggable-plus#93]
复现地址: https://stackblitz.com/edit/vitejs-vite-kyt3kp

步骤：
拖拽左侧的 input 到表单，然后在拖拽左侧的 rate 到表单中 input 的下面。rate 会放置在 input 上面。

```typescript
const onDragAdd = (evt: SortableEvent) => {
  console.log(evt.newIndex)
}
```
监听 add 事件，打印出的 evt.newIndex 是正确的。

**Comment by kanocence** [comment]
发现`evt.newDraggableIndex` 和 `evt.newIndex` 不一致的时候会出现顺序错误
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/61108370/6bb89e66-c6d1-4fee-8899-ca005bc2cd54)

**Comment by Aaron-zon** [comment]
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/47178158/71a79341-8318-4893-919e-a832fd22e498)
删掉这个，或将下面的列也设置成ul。
这不是自定义克隆的问题，#98

**Comment by kanocence** [comment]
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/61108370/76b07e68-4e45-48e1-94c4-1fac3ff24029)
换成div已解决👍👍
