### ISSUE TITLE
Restricted column in custom Clone

### ISSUE THREAD

**Issue by web-mm** [Alfred-Skyblue/vue-draggable-plus#97]
I have a vue-drggable list in a for-loop and each list contains multiple items. Items can be cloned from one list to another. I don't want to allow the items to be moved to first position in any list. Is there any inbuilt functionality to achieve this?

First index in the each list should be irreplaceable.

**Comment by Aaron-zon** [comment]
https://alfred-skyblue.gitee.io/vue-draggable-plus/en/api/
filter  Selector for items that should not be draggable

**Comment by manish-maersk** [comment]
I want each item to be draggable but first item in each list should not be replaceable.

**Comment by Aaron-zon** [comment]
> I want each item to be draggable but first item in each list should not be replaceable.

set a special class for the first item in each column, and then handle it through the filter in the API to set this class as an element that is not draggable.
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/47178158/20fc2185-8bdf-4051-918f-c3c791260941)
