### ISSUE TITLE
当使用ul、li作为拖拽元素，进行多列表拖拽时元素顺序异常

### ISSUE THREAD

**Issue by Aaron-zon** [Alfred-Skyblue/vue-draggable-plus#98]
例子：https://stackblitz.com/edit/vitejs-vite-epfmzq?file=src%2FApp.vue
以上用一个简单的双列表的组件模式写了个例子，只要使用ul、li、ol在其他模式也会有相同的效果。

### **流程：**
将第一个容器中的元素**拖拽到第二个容器的最后**，鼠标抬起后该元素移动到了第二个容器的首位。

### **预期：**
鼠标抬起后该元素停留在第二个容器最后的位置
![msedge_cwY1znxRIP](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/47178158/77558bfc-c7af-480d-b050-7cfbb12abd56)

**Comment by Alfred-Skyblue** [comment]
这是 Sortablejs 的问题，请规范使用嵌套元素，如果目标元素为ul，请确保子元素为li，如果目标元素为div，请确保子元素为div。

**Comment by Aaron-zon** [comment]
![chrome_dmDBy95QGr](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/47178158/10fd8a17-a4e5-4041-afcc-38ffd02b8ec2)

谢谢，我也觉得这种嵌套关系应该规范一些，不过Sortablejs看起来已经解决这个问题了，对ul、li这种结构应该有特殊的处理

![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/47178158/c9b03151-08d2-420c-bf7f-fab5dc0149c0)
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/47178158/f3813fba-3d97-4bb2-a783-650df2c4e970)

在使用ul、li时如果insertElement使用evt.newIndex则可以让元素显示在正常的位置上。

![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/47178158/784137e8-0c5c-4543-947a-5d778ecf9fff)

不过我还没太搞清楚newIndex和newDraggableIndex代表什么，这样写可能会有其他问题，请问您知道这两个分别代表什么吗？

**Comment by Alfred-Skyblue** [comment]
![image](https://github.com/Alfred-Skyblue/vue-draggable-plus/assets/55641773/a3b71e16-7656-43cb-ba99-19c6f0956f2c)

实际上问题并没有被解决，newIndex为最新的index，newDraggableIndex为当前列表中排除不可拖拽项意外的index，在上述的案例中，我猜测您直接使用了 sortablejs，但是它与数据没有绑定关系，实际上获取到的 newDraggableIndex 依然为0，当我们在vue中使用时，需要对数据进行绑定，此时如果 newDraggableIndex 为0，将会把数据移动到数组的第一项。

**Comment by Aaron-zon** [comment]
> ![图像](https://private-user-images.githubusercontent.com/55641773/305699031-a3b71e16-7656-43cb-ba99-19c6f0956f2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDczNDMsIm5iZiI6MTcwODI0NzA0MywicGF0aCI6Ii81NTY0MTc3My8zMDU2OTkwMzEtYTNiNzFlMTYtNzY1Ni00M2NiLWJhOTktMTljNmYwOTU2ZjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA5MDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNjljYzI2ODYxMjc5NjA1ZDRlNWY4MTE1YWI2ZmFmYTA4ZDViZjE0MTQ3ODAxOTlhM2I5N2Q0YTQ2OTBiNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d-PAr47MzjHUVWhMVTrfN2eljeQGBQK4OtCNQ7oUaE8)
> 
> 其实问题并没有被解决，newIndex为最新的索引，newDraggableIndex为当前列表中排除不可拖拽关系意外的索引，在上述的案例中，我猜测你直接使用了sortablejs，但是它与数据没有绑定，实际上获取到的newDraggableIndex仍然为0，当我们在vue中使用时，需要对数据进行绑定，此时如果newDraggableIndex为0，就会把数据移动到备份的第一个。

谢谢，那这样的话我使用evt.newIndex的修改方式，在当前列表有不可拖拽元素时可能会出问题是吗

**Comment by Alfred-Skyblue** [comment]
> 谢谢，那这样的话我使用evt.newIndex的修改方式，在当前列表有不可拖拽元素时可能会出问题是吗

是的，参考 https://github.com/Alfred-Skyblue/vue-draggable-plus/pull/44
